language: go
sudo: required

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install:
  - sudo sh -c "echo 'deb https://labs.consol.de/repo/stable/ubuntu $(lsb_release -cs) main' >> /etc/apt/sources.list"
  - wget -q "https://labs.consol.de/repo/stable/RPM-GPG-KEY" -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install naemon-dev

script:
  -  make citest
