package nagios4

const (
	NebcallbackProcessData = iota
	NebcallbackTimedEventData
	NebcallbackLogData
	NebcallbackSystemCommandData
	NebcallbackEventHandlerData
	NebcallbackNotificationData
	NebcallbackServiceCheckData
	NebcallbackHostCheckData
	NebcallbackCommentData
	NebcallbackDowntimeData
	NebcallbackFlappingData
	NebcallbackProgramStatusData
	NebcallbackHostStatusData
	NebcallbackServiceStatusData
	NebcallbackAdaptiveProgramData
	NebcallbackAdaptiveHostData
	NebcallbackAdaptiveServiceData
	NebcallbackExternalCommandData
	NebcallbackAggregatedStatusData
	NebcallbackRetentionData
	NebcallbackContactNotificationData
	NebcallbackContactNotificationMethodData
	NebcallbackAcknowledgementData
	NebcallbackStateChangeData
	NebcallbackContactStatusData
	NebcallbackAdaptiveContactData
)
