name: citest
on:
  push:
  pull_request:
  schedule:
    - cron: '30 4 * * 1'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.20.x
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses:  abbbi/github-actions-tune@v1
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v5
    - run: |
        sudo sh -c 'echo "deb [signed-by=/etc/apt/trusted.gpg.d/naemon.asc] http://download.opensuse.org/repositories/home:/naemon/xUbuntu_$(lsb_release -rs)/ ./" >> /etc/apt/sources.list.d/naemon-stable.list'
        sudo curl -s -o /etc/apt/trusted.gpg.d/naemon.asc "https://build.opensuse.org/projects/home:naemon/signing_keys/download?kind=gpg"
        sudo apt-get update
        sudo apt-get -y install naemon-dev
    - run: make clean
    #- run: make updatedeps
    #  if: github.event_name != 'pull_request'
    - run: make citest
